#!/usr/bin/env python3
"""Author the synthetic PS1 BIN/CUE fixture (NORMALIZERS.md row
`ps1-bincue`).

The committed base fixture's substance is Mode 2 Form 1 sector-format
handling — a normalizer must remap the raw 2352-byte sector stream to the
2048-byte user-data stream the existing `iso9660` normalizer already walks.
The test suite derives deterministic mixed Form-2 sectors from these bytes
to prove the lossless sector API without duplicating a second carrier. This
seedtool authors both base representations in one deterministic run, plus
the structural anchor:

  1. pycdlib authors a small PS1-shaped XA ISO (`interchange_level=1,
     xa=True`): SYSTEM.CNF-style boot stub, a few data files, an empty
     file, a nested dir. The 2048-byte-sector ISO is the user-data truth
     (and the byte-differential the normalizer is checked against).
  2. The seedtool wraps each 2048-byte block into a 2352-byte Mode 2
     Form 1 raw sector (sync + BCD address from sector index + 8-byte
     XA subheader + 2048 user data + EDC + ECC). Writes `game.bin` and
     `game.cue` (single data track MODE2/2352, INDEX 01 00:00:00).
  3. chdman `createcd` accepts the wrapped .bin/.cue as MODE2_RAW —
     a third-party confirmation the raw structure is valid, not a
     fixture only the normalizer happens to parse. The .chd is
     discarded; it is the *acceptance* that matters, not the bytes.
  4. 7-Zip extracts the inner ISO's file tree to `reference/` (the
     byte-fidelity substrate verify.py's check 4 reads through the
     normalizer's ByteView composed with iso9660).
  5. Expected manifest is authored from pycdlib's OWN directory
     records (the second independent reader, never the parser under
     test); source.name = "game.bin", source.sha256 + size = the
     inner ISO's (the ByteView decodes to it byte-identically).

The committed artifacts (under fixtures/ps1_bincue/synthetic/):
  - game.bin              raw Mode 2 Form 1 sector stream
  - game.cue              cue sheet (single data track)
  - synthetic.iso         the inner 2048-byte ISO (for inspection /
                          composed-with-iso9660 walks)
  - expected.manifest.json
  - reference/            extracted file tree of the inner ISO

Like make_iso_fixture, this is NOT byte-reproducible across runs
(pycdlib stamps volume/record dates): the image, manifest, and
reference bytes are authored together in one run and committed
together.
"""

import hashlib
import io
import re
import shutil
import struct
import subprocess
import sys
import zlib
from importlib.metadata import version as dist_version
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pycdlib

from substratum.contract import FileEntry, FileSource, FileTree, canonical_manifest, sha256_of

GENERATOR = "make_ps1_bincue_fixture v1"
TOOL_TIMEOUT_SECONDS = 300

ROOT = Path(__file__).resolve().parent.parent
CHDMAN = ROOT / "tools" / "chdman" / "chdman.exe"

# --- CD-ROM Mode 2 Form 1 sector layout (ECMA-130 / Yellow Book) ----------
SECTOR_SIZE = 2352
SYNC_LEN = 12
HEADER_LEN = 4
XA_SUB_LEN = 8
USER_LEN = 2048
EDC_LEN = 4
ECC_LEN = 276  # 12+4+8+2048+4+276 = 2352 (was 280 in the original spec; corrected
               # after the 2026-07-23 chdman probe confirmed ECC=276 is what
               # makes MODE2_RAW round-trip)
assert SYNC_LEN + HEADER_LEN + XA_SUB_LEN + USER_LEN + EDC_LEN + ECC_LEN == SECTOR_SIZE

SYNC = b"\x00" + b"\xFF" * 10 + b"\x00"  # 12 bytes
# XA Mode 2 Form 1 subheader: file#, channel#, submode (0x08 = Form 1),
# coding info (0x00). Repeated twice (4 + 4).
XA_SUB = bytes([0x00, 0x00, 0x08, 0x00]) * 2  # 8 bytes
LEAD_IN_SECTORS = 150  # 2-second pregap (CD standard), as MODE2_RAW zero sectors


def _bcd(n: int) -> int:
    """One-byte BCD: tens nibble << 4 | ones nibble (max 99)."""
    return ((n // 10) << 4) | (n % 10)


def _blob(tag: bytes, size: int) -> bytes:
    """Deterministic pseudo-random payload (sha256 chain — stable across
    Python versions, unlike random.Random)."""
    out, h = bytearray(), tag
    while len(out) < size:
        h = hashlib.sha256(h).digest()
        out += h
    return bytes(out[:size])


# --- pycdlib-authored inner ISO (PS1-shaped; tier-1, committed) ------------

DIRS = ["/BOOT", "/DATA", "/DATA/SUB"]

FILES = [
    (
        "/SYSTEM.CNF;1",
        b"BOOT = cdrom0:\\BOOT\\APP.ELF;1\r\nVER = 1.00\r\nVMODE = NTSC\r\n",
    ),
    (
        "/README.TXT;1",
        b"Substratum synthetic PS1 BIN/CUE fixture. Authored by seedtools/"
        b"make_ps1_bincue_fixture.py; contents are generated bytes, public domain.\n",
    ),
    ("/BOOT/APP.ELF;1", _blob(b"substratum-ps1-app", 100_000)),
    ("/DATA/A.BIN;1", bytes(range(256))),
    ("/DATA/B.BIN;1", b"\x00\x01\x02\x03" * 512),
    ("/DATA/EMPTY.BIN;1", b""),
    ("/DATA/SUB/C.DAT;1", _blob(b"substratum-ps1-c", 5_000)),
]


def _canonical(iso_path: str) -> str:
    """pycdlib iso_path -> manifest path: strip leading '/', strip version."""
    return iso_path.lstrip("/").split(";", 1)[0]


def author_iso(iso_path: Path) -> None:
    """pycdlib authors a PS1-shaped XA ISO (interchange level 1, XA flag
    set — the user-data stream a PS1 disc carries)."""
    iso = pycdlib.PyCdlib()
    iso.new(interchange_level=1, xa=True, vol_ident="SUBSTRATUM_PS1", joliet=False, rock_ridge=False)
    for d in DIRS:
        iso.add_directory(d)
    for path, data in FILES:
        iso.add_fp(io.BytesIO(data), len(data), iso_path=path)
    iso.write(str(iso_path))
    iso.close()


def entries_from_pycdlib(iso_path: Path) -> list[FileEntry]:
    """Re-open the ISO from disk; walk pycdlib's parsed records for
    extent locations + data lengths. This is the second independent reader —
    never the parser under test."""
    iso = pycdlib.PyCdlib()
    iso.open(str(iso_path))
    block = iso.pvd.logical_block_size()
    entries: list[FileEntry] = []
    for dirname, dirlist, filelist in iso.walk(iso_path="/"):
        base = dirname.rstrip("/")
        for name in dirlist:
            rec = iso.get_record(iso_path=f"{base}/{name}")
            entries.append(
                FileEntry(
                    _canonical(f"{base}/{name}"),
                    "dir",
                    rec.extent_location() * block,
                    rec.get_data_length(),
                )
            )
        for name in filelist:
            rec = iso.get_record(iso_path=f"{base}/{name}")
            entries.append(
                FileEntry(
                    _canonical(f"{base}/{name}"),
                    "file",
                    rec.extent_location() * block,
                    rec.get_data_length(),
                )
            )
    iso.close()
    return sorted(entries, key=lambda e: e.path)


def sevenzip_version() -> str:
    out = subprocess.run(
        ["7z", "i"], capture_output=True, text=True, encoding="utf-8",
        errors="replace", timeout=TOOL_TIMEOUT_SECONDS,
    ).stdout
    banner = next(line for line in out.splitlines() if line.strip())
    m = re.match(r"7-Zip (\S+) \((\w+)\).*: (\d{4}-\d{2}-\d{2})\s*$", banner.strip())
    if not m:
        raise SystemExit(f"cannot parse 7z banner: {banner!r}")
    return f"7-Zip {m.group(1)} ({m.group(2)}) {m.group(3)}"


def chdman_version() -> str:
    out = subprocess.run(
        [str(CHDMAN), "--help"], capture_output=True, text=True,
        encoding="utf-8", errors="replace", timeout=TOOL_TIMEOUT_SECONDS,
    ).stdout
    # First line: "chdman - MAME Compressed Hunks of Data (CHD) manager 0.288 (mame0288)"
    return out.splitlines()[0].split("manager ")[1].strip()


def wrap_sector(user: bytes, index: int) -> bytes:
    """Wrap a 2048-byte user block into a 2352-byte Mode 2 Form 1 raw
    sector (sync + BCD address + XA subheader + user + EDC + ECC).

    EDC is the real CRC-32 over [0, 2072) of the sector
    (sync + header + subheader + user) — see ECMA-130 § 7.2.
    ECC is zero-filled: chdman only checks structure for the
    acceptance proof, and the byte-fidelity gate is pycdlib's ISO
    content (which is independent of ECC zeros).
    """
    frame = index % 75
    second = (index // 75) % 60
    minute = index // (75 * 60)
    header = bytes([_bcd(minute), _bcd(second), _bcd(frame), 0x02])  # mode = 2
    pre_edc = SYNC + header + XA_SUB + user  # 12+4+8+2048 = 2072 bytes
    edc = struct.pack("<I", zlib.crc32(pre_edc) & 0xFFFFFFFF)
    ecc = b"\x00" * ECC_LEN
    assert len(pre_edc) + len(edc) + len(ecc) == SECTOR_SIZE
    return pre_edc + edc + ecc


def author_bin_cue(iso_path: Path, bin_path: Path, cue_path: Path) -> int:
    """Wrap the inner ISO's user data into raw MODE2_RAW sectors and
    write .bin + .cue. Returns the number of data sectors written.

    The inner ISO is the 2048-byte user-data stream; reading it
    block-by-block and wrapping each block is the exact operation the
    normalizer under test must invert (and prove byte-exact via the
    gate's fidelity check)."""
    data = iso_path.read_bytes()
    if len(data) % USER_LEN != 0:
        raise SystemExit(f"inner ISO {iso_path} is not 2048-aligned ({len(data)} bytes)")
    n_sectors = len(data) // USER_LEN

    chunks = []
    for i in range(n_sectors):
        user = data[i * USER_LEN : (i + 1) * USER_LEN]
        chunks.append(wrap_sector(user, i))

    bin_path.write_bytes(b"".join(chunks))
    # write_bytes, not write_text: write_text maps \n to the platform newline,
    # so on this Windows host it silently emitted a CRLF .cue.
    cue_path.write_bytes(
        f'FILE "{bin_path.name}" BINARY\n  TRACK 01 MODE2/2352\n'
        f"    INDEX 01 00:00:00\n".encode("ascii")
    )
    return n_sectors


def chdman_accept(bin_path: Path, cue_path: Path) -> None:
    """Structural anchor: chdman `createcd` must accept the wrapped
    .bin/.cue without error. Confirms a third-party tool reads the
    hand-authored raw structure as MODE2_RAW. The .chd is discarded."""
    if not CHDMAN.exists():
        raise SystemExit(f"chdman not vendored at {CHDMAN}; run seedtools/vendor_tools.py")
    out_chd = bin_path.parent / "_structural_anchor.chd"
    try:
        subprocess.run(
            [str(CHDMAN), "createcd", "-i", str(cue_path), "-o", str(out_chd)],
            capture_output=True, check=True, text=True, encoding="utf-8", errors="replace",
            timeout=TOOL_TIMEOUT_SECONDS,
        )
        info = subprocess.run(
            [str(CHDMAN), "info", "-i", str(out_chd)],
            capture_output=True, check=True, text=True, encoding="utf-8", errors="replace",
            timeout=TOOL_TIMEOUT_SECONDS,
        ).stdout
        # Reject anything that isn't MODE2_RAW (e.g. MODE1 / untyped) —
        # the structural-anchor must confirm the mode byte was read.
        if "MODE2_RAW" not in info:
            raise SystemExit(f"chdman info does not show MODE2_RAW:\n{info}")
    finally:
        out_chd.unlink(missing_ok=True)


def extract_reference(iso_path: Path, reference: Path) -> None:
    """7-Zip extracts the inner ISO's file tree to reference/ (same
    pattern as the iso9660 unit; no duplication, the .iso is the
    ground truth and reference/ is the byte-fidelity substrate)."""
    subprocess.run(
        ["7z", "x", "-tiso", "-sccUTF-8", "-y", f"-o{reference}", str(iso_path)],
        capture_output=True, text=True, encoding="utf-8", errors="replace", check=True,
        timeout=TOOL_TIMEOUT_SECONDS,
    )
    for p in sorted(reference.rglob("*"), reverse=True):
        if ";" in p.name:
            p.rename(p.with_name(p.name.split(";", 1)[0]))


def main() -> None:
    if not CHDMAN.exists():
        raise SystemExit(f"chdman not vendored at {CHDMAN}; run seedtools/vendor_tools.py")

    out = ROOT / "fixtures" / "ps1_bincue" / "synthetic"
    reference = out / "reference"
    if reference.exists():
        # Wipe stale extracted bytes from a prior run; pycdlib's
        # record dates mean the new .iso is byte-different each run.
        shutil.rmtree(reference)
    out.mkdir(parents=True, exist_ok=True)

    iso_path = out / "synthetic.iso"
    bin_path = out / "game.bin"
    cue_path = out / "game.cue"

    # 1. inner ISO (the byte-differential; committed)
    author_iso(iso_path)

    # 2. wrap 2048 -> 2352 Mode 2 Form 1 raw sectors; .bin + .cue
    n_sectors = author_bin_cue(iso_path, bin_path, cue_path)

    # 3. structural anchor: chdman must accept
    chdman_accept(bin_path, cue_path)

    # 4. extract reference/ via 7z (byte-fidelity substrate)
    extract_reference(iso_path, reference)

    # 5. expected manifest: entries from pycdlib (second reader);
    #    source.name = "game.bin", source.sha256/size = inner ISO
    #    (the ByteView decodes to it byte-identically).
    entries = entries_from_pycdlib(iso_path)
    tools = {
        "7z": sevenzip_version(),
        "chdman": chdman_version(),
        "pycdlib": dist_version("pycdlib"),
        "generator": GENERATOR,
    }
    tree = FileTree(source=FileSource(iso_path), format="ps1-bincue", entries=tuple(entries))
    manifest = canonical_manifest(tree, "game.bin", sha256_of(iso_path), tools)
    (out / "expected.manifest.json").write_bytes(manifest)

    print(
        f"wrote {bin_path} ({bin_path.stat().st_size} bytes, {n_sectors} sectors), "
        f"{iso_path.name} ({iso_path.stat().st_size} bytes), "
        f"{sum(1 for e in entries if e.kind == 'file')} files / "
        f"{sum(1 for e in entries if e.kind == 'dir')} dirs; tools={tools}"
    )


if __name__ == "__main__":
    main()
