#!/usr/bin/env python3
"""Author the synthetic ISO9660 fixture (S1; DESIGN.md § 5 tier 1).

Authors a small plain ISO9660 image (interchange level 1, no Joliet, no
Rock Ridge — the PS2-mastering shape) with pycdlib, then builds the
expected manifest from pycdlib's OWN directory records (the second
independent reader — never from substratum's parser) and stages reference
bytes via 7-Zip extraction (the differential tool), cross-checking
names + sizes between the two readers before anything is written.

Writes fixtures/iso9660/synthetic/{synthetic.iso, expected.manifest.json,
reference/<files>}.

Unlike the toy seedtool this is NOT byte-reproducible across runs
(pycdlib stamps volume/record dates): image, manifest, and reference
bytes are authored together in one run and committed together.
"""

import hashlib
import io
import re
import subprocess
import sys
from importlib.metadata import version as dist_version
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pycdlib

from substratum.contract import FileEntry, FileSource, FileTree, canonical_manifest, sha256_of

GENERATOR = "make_iso_fixture v1"

DIRS = ["/BOOT", "/DATA", "/DATA/SUB"]


def _blob(tag: bytes, size: int) -> bytes:
    """Deterministic pseudo-random payload (sha256 chain — stable forever,
    unlike random.Random across Python versions)."""
    out, h = bytearray(), tag
    while len(out) < size:
        h = hashlib.sha256(h).digest()
        out += h
    return bytes(out[:size])


FILES = [
    (
        "/SYSTEM.CNF;1",
        b"BOOT2 = cdrom0:\\BOOT\\APP.ELF;1\r\nVER = 1.00\r\nVMODE = PAL\r\n",
    ),
    (
        "/README.TXT;1",
        b"Substratum synthetic ISO9660 fixture (S1). Authored by seedtools/"
        b"make_iso_fixture.py; contents are generated bytes, public domain.\n",
    ),
    ("/BOOT/APP.ELF;1", _blob(b"substratum-s1-app", 100_000)),
    ("/DATA/A.BIN;1", bytes(range(256))),
    ("/DATA/B.BIN;1", b"\x00\x01\x02\x03" * 512),
    ("/DATA/EMPTY.BIN;1", b""),
    ("/DATA/SUB/C.DAT;1", _blob(b"substratum-s1-c", 5_000)),
]


def _canonical(iso_path: str) -> str:
    """pycdlib iso_path -> manifest path: strip leading '/', strip version."""
    return iso_path.lstrip("/").split(";", 1)[0]


def sevenzip_version() -> str:
    out = subprocess.run(
        ["7z", "i"], capture_output=True, text=True, encoding="utf-8", errors="replace"
    ).stdout
    banner = next(line for line in out.splitlines() if line.strip())
    # "7-Zip 26.02 (x64) : Copyright (c) 1999-2026 Igor Pavlov : 2026-06-25"
    m = re.match(r"7-Zip (\S+) \((\w+)\).*: (\d{4}-\d{2}-\d{2})\s*$", banner.strip())
    if not m:
        raise SystemExit(f"cannot parse 7z banner: {banner!r}")
    return f"7-Zip {m.group(1)} ({m.group(2)}) {m.group(3)}"


def author_iso(iso_path: Path) -> None:
    iso = pycdlib.PyCdlib()
    iso.new(interchange_level=1, vol_ident="SUBSTRATUM1")
    for d in DIRS:
        iso.add_directory(d)
    for path, data in FILES:
        iso.add_fp(io.BytesIO(data), len(data), iso_path=path)
    iso.write(str(iso_path))
    iso.close()


def entries_from_pycdlib(iso_path: Path) -> list[FileEntry]:
    """The second independent reader: re-open from disk, walk pycdlib's
    parsed records for extent locations + data lengths."""
    iso = pycdlib.PyCdlib()
    iso.open(str(iso_path))
    block = iso.pvd.logical_block_size()
    entries: list[FileEntry] = []
    for dirname, dirlist, filelist in iso.walk(iso_path="/"):
        base = dirname.rstrip("/")
        for name in dirlist:
            rec = iso.get_record(iso_path=f"{base}/{name}")
            entries.append(
                FileEntry(
                    _canonical(f"{base}/{name}"),
                    "dir",
                    rec.extent_location() * block,
                    rec.get_data_length(),
                )
            )
        for name in filelist:
            rec = iso.get_record(iso_path=f"{base}/{name}")
            entries.append(
                FileEntry(
                    _canonical(f"{base}/{name}"),
                    "file",
                    rec.extent_location() * block,
                    rec.get_data_length(),
                )
            )
    iso.close()
    return sorted(entries, key=lambda e: e.path)


def listing_from_7z(iso_path: Path) -> dict[str, tuple[str, int]]:
    """The differential tool's view: {path: (kind, size)}."""
    out = subprocess.run(
        ["7z", "l", "-slt", "-tiso", "-sccUTF-8", str(iso_path)],
        capture_output=True, text=True, encoding="utf-8", errors="replace", check=True,
    ).stdout
    body = out.split("----------", 1)[1]
    listing: dict[str, tuple[str, int]] = {}
    for block in body.split("\n\n"):
        fields = dict(
            line.split(" = ", 1) for line in block.splitlines() if " = " in line
        )
        if "Path" not in fields:
            continue
        path = fields["Path"].replace("\\", "/").split(";", 1)[0]
        kind = "dir" if fields.get("Folder") == "+" else "file"
        size = int(fields.get("Size") or 0)
        listing[path] = (kind, size)
    return listing


def extract_reference(iso_path: Path, reference: Path) -> None:
    subprocess.run(
        ["7z", "x", "-tiso", "-sccUTF-8", "-y", f"-o{reference}", str(iso_path)],
        capture_output=True, text=True, encoding="utf-8", errors="replace", check=True,
    )
    # normalize any ISO9660 version suffixes 7z may keep in extracted names
    for p in sorted(reference.rglob("*"), reverse=True):
        if ";" in p.name:
            p.rename(p.with_name(p.name.split(";", 1)[0]))


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "fixtures" / "iso9660" / "synthetic"
    reference = out / "reference"
    out.mkdir(parents=True, exist_ok=True)
    iso_path = out / "synthetic.iso"

    author_iso(iso_path)
    entries = entries_from_pycdlib(iso_path)

    # cross-check reader #2 (pycdlib) against the differential tool (7z)
    listing = listing_from_7z(iso_path)
    ours = {e.path: (e.kind, e.size) for e in entries}
    if set(ours) != set(listing):
        raise SystemExit(f"7z/pycdlib listing mismatch: {set(ours) ^ set(listing)}")
    for path, (kind, size) in ours.items():
        zkind, zsize = listing[path]
        if kind != zkind or (kind == "file" and size != zsize):
            raise SystemExit(f"7z/pycdlib disagree on {path}: {kind},{size} vs {zkind},{zsize}")

    extract_reference(iso_path, reference)
    for e in entries:
        if e.kind != "file":
            continue
        ref = reference / e.path
        if not ref.is_file() or ref.stat().st_size != e.size:
            raise SystemExit(f"reference bytes missing/short for {e.path}")

    tools = {"7z": sevenzip_version(), "pycdlib": dist_version("pycdlib"), "generator": GENERATOR}
    tree = FileTree(source=FileSource(iso_path), format="iso9660", entries=tuple(entries))
    manifest = canonical_manifest(tree, "synthetic.iso", sha256_of(iso_path), tools)
    (out / "expected.manifest.json").write_bytes(manifest)
    print(f"wrote {iso_path} ({iso_path.stat().st_size} bytes), "
          f"{sum(1 for e in entries if e.kind == 'file')} files / "
          f"{sum(1 for e in entries if e.kind == 'dir')} dirs, tools={tools}")


if __name__ == "__main__":
    main()
