#!/usr/bin/env python3
"""Author the synthetic Saturn / Dreamcast raw (2352-byte Mode 1) fixture
(NORMALIZERS.md row `saturn/dc-raw`).

The unit's substance is Mode 1 sector-format handling — a normalizer must
strip the per-sector overhead (sync + header prefix, EDC + reserved + ECC
trailer) of a 2352-byte raw Mode 1 image to recover the 2048-byte
ISO9660 user-data stream the existing `iso9660` normalizer already walks.
This seedtool authors both representations in one deterministic run, plus
the structural anchor:

  1. pycdlib authors a small ISO (`interchange_level=1`, `xa=False` —
     a plain Mode 1 disc, not XA): a SYSTEM.CNF-style boot stub, a few
     data files, an empty file, a nested dir, an incompressible blob.
     The 2048-byte-sector ISO is the user-data truth (and the
     byte-differential the normalizer is checked against).
  2. The seedtool wraps each 2048-byte block into a 2352-byte Mode 1 raw
     sector (sync + BCD address header[mode=1] + user + EDC + reserved
     + ECC). Writes `game_2352.bin` — the whole file is one contiguous
     data track, no `.cue`.
  3. 7-Zip `l -slt -tiso` on the remapped inner stream (we strip the
     raw ourselves, stdlib) confirms the recovered 2048 stream is a
     real ISO — a third-party confirmation the hand-authored raw
     structure is valid, not a fixture only the normalizer parses. The
     temp ISO is discarded; it is the acceptance that matters.
  4. 7-Zip extracts the inner ISO's file tree to `reference/` (the
     byte-fidelity substrate verify.py's check 4 reads through the
     normalizer's ByteView composed with iso9660).
  5. Expected manifest is authored from pycdlib's OWN directory records
     (the second independent reader, never the parser under test);
     source.name = "game_2352.bin", source.sha256 + size = the inner
     ISO's (the ByteView decodes to it byte-identically).

The committed artifacts (under fixtures/saturn_dc_raw/synthetic/):
  - game_2352.bin         raw Mode 1 sector stream (the disc image)
  - synthetic.iso         the inner 2048-byte ISO (for inspection)
  - expected.manifest.json
  - reference/            extracted file tree of the inner ISO

Like make_iso_fixture / make_ps1_bincue_fixture, this is NOT byte-
reproducible across runs (pycdlib stamps volume/record dates): the image,
manifest, and reference bytes are authored together in one run and
committed together.
"""

import hashlib
import io
import re
import shutil
import struct
import subprocess
import sys
import zlib
from importlib.metadata import version as dist_version
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pycdlib

from substratum.contract import FileEntry, FileSource, FileTree, canonical_manifest, sha256_of

GENERATOR = "make_saturn_dc_raw_fixture v1"
TOOL_TIMEOUT_SECONDS = 300

ROOT = Path(__file__).resolve().parent.parent

# --- CD-ROM Mode 1 sector layout (ECMA-130 / Yellow Book) ------------------
SECTOR_SIZE = 2352
SYNC_LEN = 12
HEADER_LEN = 4
USER_LEN = 2048
EDC_LEN = 4
RESERVED_LEN = 8  # Mode 1 reserves 8 bytes between EDC and ECC
ECC_LEN = 276
USER_START = SYNC_LEN + HEADER_LEN  # 16
USER_END = USER_START + USER_LEN  # 2064
assert SYNC_LEN + HEADER_LEN + USER_LEN + EDC_LEN + RESERVED_LEN + ECC_LEN == SECTOR_SIZE

SYNC = b"\x00" + b"\xFF" * 10 + b"\x00"  # 12 bytes


def _bcd(n: int) -> int:
    """One-byte BCD: tens nibble << 4 | ones nibble (max 99)."""
    return ((n // 10) << 4) | (n % 10)


def _blob(tag: bytes, size: int) -> bytes:
    """Deterministic pseudo-random payload (sha256 chain — stable across
    Python versions, unlike random.Random)."""
    out, h = bytearray(), tag
    while len(out) < size:
        h = hashlib.sha256(h).digest()
        out += h
    return bytes(out[:size])


# --- pycdlib-authored inner ISO (Mode 1; tier-1, committed) ----------------

DIRS = ["/BOOT", "/DATA", "/DATA/SUB"]

FILES = [
    (
        "/SYSTEM.CNF;1",
        b"BOOT = cdrom:\\BOOT\\APP.BIN;1\r\nVER = 1.00\r\nVMODE = NTSC\r\n",
    ),
    (
        "/README.TXT;1",
        b"Substratum synthetic Saturn/Dreamcast raw fixture. Authored by seedtools/"
        b"make_saturn_dc_raw_fixture.py; contents are generated bytes, public domain.\n",
    ),
    ("/BOOT/APP.BIN;1", _blob(b"substratum-saturn-app", 100_000)),
    ("/DATA/A.BIN;1", bytes(range(256))),
    ("/DATA/B.BIN;1", b"\x00\x01\x02\x03" * 512),
    ("/DATA/EMPTY.BIN;1", b""),
    ("/DATA/SUB/C.DAT;1", _blob(b"substratum-saturn-c", 5_000)),
]


def _canonical(iso_path: str) -> str:
    """pycdlib iso_path -> manifest path: strip leading '/', strip version."""
    return iso_path.lstrip("/").split(";", 1)[0]


def author_iso(iso_path: Path) -> None:
    """pycdlib authors a plain ISO9660 (interchange level 1, no XA) — the
    user-data stream a Saturn CD / Dreamcast GD-ROM data track carries."""
    iso = pycdlib.PyCdlib()
    iso.new(interchange_level=1, xa=False, vol_ident="SUBSTRATUM_SATDC", joliet=False, rock_ridge=False)
    for d in DIRS:
        iso.add_directory(d)
    for path, data in FILES:
        iso.add_fp(io.BytesIO(data), len(data), iso_path=path)
    iso.write(str(iso_path))
    iso.close()


def entries_from_pycdlib(iso_path: Path) -> list[FileEntry]:
    """Re-open the ISO from disk; walk pycdlib's parsed records for
    extent locations + data lengths. This is the second independent reader —
    never the parser under test."""
    iso = pycdlib.PyCdlib()
    iso.open(str(iso_path))
    block = iso.pvd.logical_block_size()
    entries: list[FileEntry] = []
    for dirname, dirlist, filelist in iso.walk(iso_path="/"):
        base = dirname.rstrip("/")
        for name in dirlist:
            rec = iso.get_record(iso_path=f"{base}/{name}")
            entries.append(
                FileEntry(
                    _canonical(f"{base}/{name}"),
                    "dir",
                    rec.extent_location() * block,
                    rec.get_data_length(),
                )
            )
        for name in filelist:
            rec = iso.get_record(iso_path=f"{base}/{name}")
            entries.append(
                FileEntry(
                    _canonical(f"{base}/{name}"),
                    "file",
                    rec.extent_location() * block,
                    rec.get_data_length(),
                )
            )
    iso.close()
    return sorted(entries, key=lambda e: e.path)


def sevenzip_version() -> str:
    out = subprocess.run(
        ["7z", "i"], capture_output=True, text=True, encoding="utf-8",
        errors="replace", timeout=TOOL_TIMEOUT_SECONDS,
    ).stdout
    banner = next(line for line in out.splitlines() if line.strip())
    m = re.match(r"7-Zip (\S+) \((\w+)\).*: (\d{4}-\d{2}-\d{2})\s*$", banner.strip())
    if not m:
        raise SystemExit(f"cannot parse 7z banner: {banner!r}")
    return f"7-Zip {m.group(1)} ({m.group(2)}) {m.group(3)}"


def wrap_sector(user: bytes, index: int) -> bytes:
    """Wrap a 2048-byte user block into a 2352-byte Mode 1 raw sector
    (sync + BCD address header[mode=1] + user + EDC + reserved + ECC).

    EDC is the real CRC-32 over [12, 2064) of the sector
    (header + user; the sync is excluded per ECMA-130 § 7.2 — note the
    spec's parenthetical "[0, 2064)" is a slip; the correct Mode 1 EDC
    covers the header too, which begins at offset 12). ECC and the 8-byte
    reserved field are zero-filled: the normalizer only slices user
    bytes, and the byte-fidelity gate is pycdlib's ISO content (which is
    independent of EDC/ECC/reserved zeros).
    """
    frame = index % 75
    second = (index // 75) % 60
    minute = index // (75 * 60)
    header = bytes([_bcd(minute), _bcd(second), _bcd(frame), 0x01])  # mode = 1
    pre_edc = SYNC + header + user  # 12+4+2048 = 2064 bytes ([0, 2064))
    edc = struct.pack("<I", zlib.crc32(pre_edc[SYNC_LEN:]) & 0xFFFFFFFF)  # over [12, 2064)
    reserved = b"\x00" * RESERVED_LEN
    ecc = b"\x00" * ECC_LEN
    assert len(pre_edc) + len(edc) + len(reserved) + len(ecc) == SECTOR_SIZE
    return pre_edc + edc + reserved + ecc


def author_bin(iso_path: Path, bin_path: Path) -> int:
    """Wrap the inner ISO's user data into raw Mode 1 sectors and write
    `game_2352.bin` (single data track, no cue). Returns the sector count.

    Reading the inner ISO block-by-block and wrapping each block is the
    exact operation the normalizer under test must invert (and prove
    byte-exact via the gate's fidelity check)."""
    data = iso_path.read_bytes()
    if len(data) % USER_LEN != 0:
        raise SystemExit(f"inner ISO {iso_path} is not 2048-aligned ({len(data)} bytes)")
    n_sectors = len(data) // USER_LEN

    chunks = []
    for i in range(n_sectors):
        user = data[i * USER_LEN : (i + 1) * USER_LEN]
        chunks.append(wrap_sector(user, i))

    bin_path.write_bytes(b"".join(chunks))
    return n_sectors


def remap_anchor(bin_path: Path, n_sectors: int) -> None:
    """Structural anchor: 7-Zip `l -slt -tiso` must recognize the remapped
    inner stream (we strip the raw ourselves, stdlib) as a real ISO.
    Confirms a third-party tool reads the hand-authored structure as an
    ISO — the .tmp.iso is discarded."""
    data = bin_path.read_bytes()
    out = bytearray()
    for i in range(n_sectors):
        sec = data[i * SECTOR_SIZE : (i + 1) * SECTOR_SIZE]
        out += sec[USER_START:USER_END]
    tmp = bin_path.parent / "_structural_anchor.iso"
    tmp.write_bytes(bytes(out))
    try:
        res = subprocess.run(
            ["7z", "l", "-slt", "-tiso", str(tmp)],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=TOOL_TIMEOUT_SECONDS,
        )
        if res.returncode != 0:
            raise SystemExit(f"7z cannot list remapped inner ISO:\n{res.stderr}")
        if "type = iso" not in res.stdout.lower():
            raise SystemExit(
                f"7z did not recognize remapped inner ISO as iso:\n{res.stdout[:500]}"
            )
    finally:
        tmp.unlink(missing_ok=True)


def extract_reference(iso_path: Path, reference: Path) -> None:
    """7-Zip extracts the inner ISO's file tree to reference/ (same pattern
    as the iso9660 / ps1-bincue units; the .iso is the ground truth and
    reference/ is the byte-fidelity substrate)."""
    subprocess.run(
        ["7z", "x", "-tiso", "-sccUTF-8", "-y", f"-o{reference}", str(iso_path)],
        capture_output=True, text=True, encoding="utf-8", errors="replace", check=True,
        timeout=TOOL_TIMEOUT_SECONDS,
    )
    for p in sorted(reference.rglob("*"), reverse=True):
        if ";" in p.name:
            p.rename(p.with_name(p.name.split(";", 1)[0]))


def main() -> None:
    out = ROOT / "fixtures" / "saturn_dc_raw" / "synthetic"
    reference = out / "reference"
    if reference.exists():
        # Wipe stale extracted bytes from a prior run; pycdlib's record
        # dates mean the new .iso is byte-different each run.
        shutil.rmtree(reference)
    out.mkdir(parents=True, exist_ok=True)

    iso_path = out / "synthetic.iso"
    bin_path = out / "game_2352.bin"

    # 1. inner ISO (the byte-differential; committed)
    author_iso(iso_path)

    # 2. wrap 2048 -> 2352 Mode 1 raw sectors -> game_2352.bin
    n_sectors = author_bin(iso_path, bin_path)

    # 3. structural anchor: 7z must recognize the remapped inner stream
    remap_anchor(bin_path, n_sectors)

    # 4. extract reference/ via 7z (byte-fidelity substrate)
    extract_reference(iso_path, reference)

    # 5. expected manifest: entries from pycdlib (second reader);
    #    source.name = "game_2352.bin", source.sha256/size = inner ISO
    #    (the ByteView decodes to it byte-identically).
    entries = entries_from_pycdlib(iso_path)
    tools = {
        "7z": sevenzip_version(),
        "pycdlib": dist_version("pycdlib"),
        "generator": GENERATOR,
    }
    tree = FileTree(source=FileSource(iso_path), format="saturn-dc-raw", entries=tuple(entries))
    manifest = canonical_manifest(tree, "game_2352.bin", sha256_of(iso_path), tools)
    (out / "expected.manifest.json").write_bytes(manifest)

    print(
        f"wrote {bin_path} ({bin_path.stat().st_size} bytes, {n_sectors} sectors), "
        f"{iso_path.name} ({iso_path.stat().st_size} bytes), "
        f"{sum(1 for e in entries if e.kind == 'file')} files / "
        f"{sum(1 for e in entries if e.kind == 'dir')} dirs; tools={tools}"
    )


if __name__ == "__main__":
    main()
