#!/usr/bin/env python3
"""Author the synthetic Wii U8 archive (.arc) fixture (NORMALIZERS.md row `wii-u8-arc`).

The unit's substance is U8 node-archive parsing. Since we are using D1 = structural self-consistency,
no third-party extraction tools are needed. The generator itself writes the expected manifest and
the reference/ directory with files.
"""

import hashlib
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from substratum.contract import FileEntry, FileSource, FileTree, canonical_manifest, sha256_of

GENERATOR = "make_wii_u8_arc_fixture v1"
ROOT = Path(__file__).resolve().parent.parent

_TAG = 0x55AA382D

def _blob(tag: bytes, size: int) -> bytes:
    """Deterministic pseudo-random payload (sha256 chain)."""
    out, h = bytearray(), tag
    while len(out) < size:
        h = hashlib.sha256(h).digest()
        out += h
    return bytes(out[:size])

# Let's define the hierarchical tree
FILES = {
    "README.TXT": b"Substratum synthetic Wii U8 archive fixture. Authored by seedtools/make_wii_u8_arc_fixture.py; contents are generated bytes, public domain.\n",
    "BOOT/APP.BIN": _blob(b"substratum-u8-app", 10_000),
    "DATA/A.BIN": bytes(range(256)),
    "DATA/B.BIN": b"\x00\x01\x02\x03" * 512,
    "DATA/EMPTY.BIN": b"",
    "DATA/SUB/C.DAT": _blob(b"substratum-u8-c", 5_000),
}

def build_archive() -> tuple[bytes, list[FileEntry]]:
    # Nodes list
    # Node structure: type (1B), name_offset (3B), data_offset / parent (4B), size / next (4B)
    # 1-based indexing for U8
    # 1: root dir, parent=1, next=10
    # 2: BOOT dir, parent=1, next=4
    # 3: BOOT/APP.BIN file, name="APP.BIN"
    # 4: DATA dir, parent=1, next=9
    # 5: DATA/A.BIN file, name="A.BIN"
    # 6: DATA/B.BIN file, name="B.BIN"
    # 7: DATA/EMPTY.BIN file, name="EMPTY.BIN"
    # 8: DATA/SUB dir, parent=4, next=10
    # 9: DATA/SUB/C.DAT file, name="C.DAT"
    # 10: README.TXT file, name="README.TXT"
    
    # We will build string table first
    strings = bytearray(b"\x00")
    name_offsets = {}
    
    names_to_add = ["BOOT", "APP.BIN", "DATA", "A.BIN", "B.BIN", "EMPTY.BIN", "SUB", "C.DAT", "README.TXT"]
    for n in names_to_add:
        name_offsets[n] = len(strings)
        strings.extend(n.encode("ascii"))
        strings.append(0)

    # Let's align data region to 0x40
    rootnode_offset = 0x20
    header_size = 10 * 12 + len(strings)
    data_offset = (rootnode_offset + header_size + 0x3F) & ~0x3F

    # Place file payloads contiguously
    cursor = data_offset
    file_info = {} # path -> (offset, size)
    # Order of files:
    # BOOT/APP.BIN
    # DATA/A.BIN
    # DATA/B.BIN
    # DATA/EMPTY.BIN
    # DATA/SUB/C.DAT
    # README.TXT
    order = [
        ("BOOT/APP.BIN", FILES["BOOT/APP.BIN"]),
        ("DATA/A.BIN", FILES["DATA/A.BIN"]),
        ("DATA/B.BIN", FILES["DATA/B.BIN"]),
        ("DATA/EMPTY.BIN", FILES["DATA/EMPTY.BIN"]),
        ("DATA/SUB/C.DAT", FILES["DATA/SUB/C.DAT"]),
        ("README.TXT", FILES["README.TXT"]),
    ]
    payloads = bytearray()
    for path, content in order:
        file_info[path] = (cursor, len(content))
        payloads.extend(content)
        cursor += len(content)

    # Now let's construct the 10 nodes
    def make_node(type_: int, name_off: int, f1: int, f2: int) -> bytes:
        return bytes([type_]) + name_off.to_bytes(3, "big") + struct.pack(">II", f1, f2)

    nodes_bytes = b"".join([
        make_node(1, 0, 1, 10), # Node 1: root dir, parent=1, next=10
        make_node(1, name_offsets["BOOT"], 1, 3), # Node 2: BOOT dir, parent=1, next=3
        make_node(0, name_offsets["APP.BIN"], file_info["BOOT/APP.BIN"][0], file_info["BOOT/APP.BIN"][1]), # Node 3
        make_node(1, name_offsets["DATA"], 1, 9), # Node 4: DATA dir, parent=1, next=9
        make_node(0, name_offsets["A.BIN"], file_info["DATA/A.BIN"][0], file_info["DATA/A.BIN"][1]), # Node 5
        make_node(0, name_offsets["B.BIN"], file_info["DATA/B.BIN"][0], file_info["DATA/B.BIN"][1]), # Node 6
        make_node(0, name_offsets["EMPTY.BIN"], file_info["DATA/EMPTY.BIN"][0], file_info["DATA/EMPTY.BIN"][1]), # Node 7
        make_node(1, name_offsets["SUB"], 4, 9), # Node 8: DATA/SUB dir, parent=4, next=9 (wait! last child is node 9, so next=9 is correct!)
        make_node(0, name_offsets["C.DAT"], file_info["DATA/SUB/C.DAT"][0], file_info["DATA/SUB/C.DAT"][1]), # Node 9
        make_node(0, name_offsets["README.TXT"], file_info["README.TXT"][0], file_info["README.TXT"][1]), # Node 10
    ])

    # Construct complete archive bytes
    # Align header part to data_offset
    header_part = struct.pack(">IIII", _TAG, rootnode_offset, header_size, data_offset) + b"\x00" * 16 + nodes_bytes + bytes(strings)
    # Pad to data_offset
    padding = b"\x00" * (data_offset - len(header_part))
    archive_bytes = header_part + padding + payloads

    # Entries list for manifest
    # paths:
    # BOOT (dir), BOOT/APP.BIN (file)
    # DATA (dir), DATA/A.BIN (file), DATA/B.BIN (file), DATA/EMPTY.BIN (file)
    # DATA/SUB (dir), DATA/SUB/C.DAT (file)
    # README.TXT (file)
    entries = [
        FileEntry("BOOT", "dir", 0, 0),
        FileEntry("BOOT/APP.BIN", "file", file_info["BOOT/APP.BIN"][0], file_info["BOOT/APP.BIN"][1]),
        FileEntry("DATA", "dir", 0, 0),
        FileEntry("DATA/A.BIN", "file", file_info["DATA/A.BIN"][0], file_info["DATA/A.BIN"][1]),
        FileEntry("DATA/B.BIN", "file", file_info["DATA/B.BIN"][0], file_info["DATA/B.BIN"][1]),
        FileEntry("DATA/EMPTY.BIN", "file", file_info["DATA/EMPTY.BIN"][0], file_info["DATA/EMPTY.BIN"][1]),
        FileEntry("DATA/SUB", "dir", 0, 0),
        FileEntry("DATA/SUB/C.DAT", "file", file_info["DATA/SUB/C.DAT"][0], file_info["DATA/SUB/C.DAT"][1]),
        FileEntry("README.TXT", "file", file_info["README.TXT"][0], file_info["README.TXT"][1]),
    ]

    return bytes(archive_bytes), entries

def main() -> None:
    out = ROOT / "fixtures" / "wii_u8_arc" / "synthetic"
    reference = out / "reference"
    out.mkdir(parents=True, exist_ok=True)
    reference.mkdir(parents=True, exist_ok=True)

    archive_bytes, entries = build_archive()
    archive_path = out / "archive.arc"
    archive_path.write_bytes(archive_bytes)

    # Write reference/ files
    for path, content in FILES.items():
        ref_file = reference / path
        ref_file.parent.mkdir(parents=True, exist_ok=True)
        ref_file.write_bytes(content)

    tools = {
        "self-consistency": "structural-proof",
        "generator": GENERATOR,
    }
    
    # expected.manifest.json
    tree = FileTree(source=FileSource(archive_path), format="wii-u8-arc", entries=tuple(entries))
    manifest = canonical_manifest(tree, "archive.arc", sha256_of(archive_path), tools)
    (out / "expected.manifest.json").write_bytes(manifest)

    print(f"wrote {archive_path} ({len(archive_bytes)} bytes)")
    print(f"expected.manifest.json generated.")

if __name__ == "__main__":
    main()
